# <center> Homework 1 </center>

# 0. Где мы сейчас?
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Jupyter_logo.svg/1200px-Jupyter_logo.svg.png" width="150">

[Jupyter Notebook](https://jupyter.org/) - интерактивная среда для запуска программного кода в браузере. Удобный инструмент для анализа данных, который используется многими специалистами по data science. Позволяет выполнять отдельные ячейки с кодом, а не всю программу сразу, что очень удобно при знакомстве с данными.

# 1. Python
> Python - это свободный интерпретируемый объектно-ориентированный расширяемый встраиваемый язык программирования очень высокого уровня 

>*(Г.Россум, Ф.Л.Дж.Дрейк, Д.С.Откидач "Язык программирования Python").*

А если без цитат, то питон - это просто очень крутой язык, созданный в 1991 году [Великодушным пожизненным диктатором](https://ru.wikipedia.org/wiki/%D0%92%D0%B5%D0%BB%D0%B8%D0%BA%D0%BE%D0%B4%D1%83%D1%88%D0%BD%D1%8B%D0%B9_%D0%BF%D0%BE%D0%B6%D0%B8%D0%B7%D0%BD%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D0%B4%D0%B8%D0%BA%D1%82%D0%B0%D1%82%D0%BE%D1%80) Гвидо ван Россумом и названный в честь любимого им шоу [Monty Python's Flying Circus](https://en.wikipedia.org/wiki/Monty_Python%27s_Flying_Circus)

<img src="https://advancelocal-adapter-image-uploads.s3.amazonaws.com/image.oregonlive.com/home/olive-media/width2048/img/tv/photo/2018/10/10/montycastjpg-7ef393e2355a42aa.jpg" width="300">

# 2. Anaconda

<img src="https://cdn-images-1.medium.com/max/1600/0*MVkCW8_Bmj-nuAnI.png" width="300">

[Сборка Anaconda](https://www.anaconda.com/products/individual) включает очень много полезных библиотек для анализа данных. 

Среди наиболее популярных библиотек:
 - <a href="http://numpy.org">Numpy</a> - это один из основных пакетов для математических вычислений. Он содержит средства для работы с многомерными массивами и высокоуровневыми математическими функциями
 - <a href="https://www.scipy.org/">SciPy</a> - научные вычисления. Методы оптимизации, интегрирования, модули обработки сигналов и изображений, статистика, линейная алгебра, сплайны, кластеризация и многое другое
 -  <a href="http://pandas.pydata.org/">Pandas</a> - основная библиотека для обработки и анализа данных. Предназначена для данных разной природы - матричных, панельных данных, временных рядов. Претендует на звание самого мощного и гибкого средства для анализа данных с открытым исходным кодом
 - <a href="http://scikit-learn.org/stable/">Scikit-learn</a> - реализация очень многих методов машинного обучения с отличной документацией. 
 - <a href="http://http://matplotlib.org/">matplotlib</a> - хорошая библиотека для визуализации данных

# 3. Задачки

## Задача 1
$N$ хоббитов делят $K$ кусков эльфийского хлеба поровну, не делящийся нацело остаток остается в корзинке у Сэма. Напишите функцию, которая принимает на вход параметры $N$ и $K$ и возвращает два числа: $x$ - cколько кусков эльфиского хлеба достанется каждому хоббиту, и $y$ - сколько кусков остаётся в корзинке.

In [442]:
def share_bread(N, K):
    return K // N, K % N


# если в функции всё верно, то после выполнения этой строчки, не должно выскакивать ошибок
assert share_bread(N=3, K=14) == (4, 2)

## Задача 2

В копях Мории хоббиты нашли стену, на которой высечены разные натуральные числа. Согласно древним сказаниям, это даты сражений. Хоббиты знают, что сражения происходили только по високосным годам. Помогите хоббитам определить, является ли год с данным числом датой великого сражения. Если это так, то верните строку "YOU SHALL PASS", иначе верните "YOU SHALL NOT PASS". Напомним, что в соответствии с хоббитским календарем, год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.

In [443]:
def leap_year(year):
    text_result = "YOU SHALL NOT PASS"
    if (year % 4 == 0) and ((year % 100 != 0) or (year % 400 == 0)):
        text_result = "YOU SHALL PASS"
    return text_result


assert leap_year(5) == "YOU SHALL NOT PASS"

## Задача 3
<img src="http://i0.kym-cdn.com/photos/images/original/001/187/255/5e9.gif" width=300>
Для могущественного магического ритуала Гендальфу необходимо быстро подсчитывать площадь своего амулета, который умеет менять размеры. Известно, что амулет имеет форму треугольника и Гендальф знает длину каждой из сторон. Напишите функцию, которая считает площадь амулета по трем сторонам.  

Подсказка: используйте формулу Герона
$$ S = \sqrt{p(p-a)(p-b)(p-c)} $$
$$ p = \frac{a + b + c}{2}$$


In [444]:
import math


def amulet_area(a, b, c):
    p = (a + b + c) / 2
    return math.sqrt(p * (p - a) * (p - b) * (p - c))


assert amulet_area(3, 4, 5) == 6

## Задача 4

Хоббиты собираются пешком идти до Мордора и им нужно подсчитать расстояние, которое им предстоит пройти. Хоббиты смогли вспомнить сразу несколько метрик расстояния: евклидово, манхэттена и косинусное, так что ваша задача - напистаь функцию под каждую из них. Важное условие - используйте только базовые функции numpy для решения.


* Евклидово расстояние
$$ d(a, b) = \sqrt{\sum_i (a_i - b_i)^2} $$
* Расстояние Манхэттена
$$ d(a, b) = \sum_i |a_i - b_i| $$
* Косинусное расстояние
$$ d(a, b) = 1 - \frac{a^\top b}{||a||_2\cdot||b||_2}$$

In [445]:
import numpy as np
import scipy.spatial.distance as ds


def cal_euclidean(a, b):

    return sum((x - y) ** 2 for x, y in zip(a, b)) ** 0.5



def cal_manhattan(a, b):

    return sum((x - y) for (x, y) in zip(a, b))



def cal_cosine(a, b):
    return ds.cosine(a, b)

In [446]:
a = np.random.randint(-10, 10, size=10)
b = np.random.randint(-10, 10, size=10)
print(cal_euclidean(a, b))
print(cal_manhattan(a, b))
print(cal_cosine(a, b))

12.727922061357855
2
0.3080840536411412


## Задача 5

Ну и напоследок, еще немного практики numpy, без которой не обходится ни один хоббит.


Создайте случайный array (`np.random.rand()`) длинной 100. Преобразуйте его так, чтобы
* Максимальный элемент(ы) был равен 1
* Минимальный элемент(ы) был равен 0
* Остальные элементы в итнтервале от 0 до 1 остаются прежними

In [447]:
import numpy as np
rng = np.random.default_rng()
my_array = rng.random((100,))
my_array[my_array.argmax()]=1
my_array[my_array.argmin()]=0

print(np.max(my_array), np.min(my_array))
print(my_array)

1.0 0.0
[0.80971018 0.32256029 0.7524858  0.53298182 0.54614787 0.78721906
 0.94617244 0.22427713 0.90917942 0.01537568 0.35576433 0.62957858
 0.14315361 0.94943553 0.89489363 0.29995426 0.96018896 0.74182861
 0.31647943 0.32387515 0.80928595 0.03494973 0.38733434 0.1678921
 0.59348778 0.72657461 0.72316997 0.36211549 0.11573248 0.63065329
 0.25242946 0.79050789 0.06022496 0.24746339 0.80335668 0.81373137
 0.40577967 0.31431135 0.64887331 0.7531836  0.48885735 0.96395372
 0.04277289 0.98505543 0.48224415 0.63936767 0.8624938  0.8804498
 0.         1.         0.15010036 0.78127793 0.44921902 0.14782212
 0.84513316 0.7728103  0.29789876 0.70401492 0.62503915 0.68438404
 0.65167331 0.20997517 0.79959866 0.19079887 0.32676255 0.55113349
 0.80062741 0.71137087 0.12411387 0.49414459 0.50406905 0.51346635
 0.02181518 0.27259045 0.19192903 0.98580859 0.25111931 0.6413427
 0.30405554 0.93510105 0.24274304 0.52621166 0.30101995 0.26270211
 0.87509977 0.82347269 0.62524332 0.41569119 0.10156843 0

Создайте array размером $5 \times 6$ с целыми числами в интервале [0,50]. Напечатайте колонку, которая содержит максимальный элемент полученной матрицы 

In [448]:
import numpy as np
rng = np.random.default_rng()
my_array = rng.integers(0,50,(5,6))

selected_column =my_array[:,(np.argmax(my_array)%6)]
print('Shape: ',my_array.shape)
print('Array')
print(my_array)
print(selected_column)

Shape:  (5, 6)
Array
[[37 20 41 31  4 39]
 [23 30  7 15 25 37]
 [22 20  1 27  6 38]
 [ 6 14 44 47  5 46]
 [25 13 37 23  0 28]]
[31 15 27 47 23]


Напишите функцию, которая принимает на вохд матрицу (array) X и возвращает все её уникальные строки в виде новой матрицы.

In [449]:
import numpy as np

def get_unique_rows(X):
    X_unique = []
    for i in range(0, np.shape(X)[0]):
        if not np.array(X[i, :]).tolist() in X_unique:
            X_unique.append(np.array(X[i, :]).tolist()) 
    return X_unique

In [450]:
V = np.random.randint(4, 6, size=(10,3))
print(np.shape(X))
print(X)

(10, 3)
[[5 5 5]
 [4 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 4]
 [5 4 5]
 [4 5 5]
 [4 5 4]
 [4 5 5]
 [5 5 5]]


In [451]:
get_unique_rows(X)

[[5, 5, 5], [4, 5, 5], [5, 5, 4], [5, 4, 5], [4, 5, 4]]